services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: project_learning_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_learning_platform
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
      - DEBUG=true
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GOOGLE_CLIENT_ID=1070207303216-8fc5a0okd7h7vlijjm0ff0sg1cd0h2lk.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c "npm ci && npm run dev"

volumes:
  postgres_data:
  redis_data:
